[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

upload_port = COM5
monitor_port = COM5

; --- ROZWIĄZANIE CRASH LOOP (NAPRAWA FLASH OPI WROOM-2) ---
; Wymuszamy bezpieczny nagłówek bootloadera i mapowanie Octal
board_build.flash_mode = dio
board_build.arduino.memory_type = opi_opi

; Mapowanie pamięci dyskowej (ZMIANA DLA OTA)
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

; Konfiguracja natywnego USB dla S3 oraz PSRAM
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ;-D BOARD_HAS_PSRAM

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    bblanchon/ArduinoJson @ ^7.0.4
    me-no-dev/AsyncTCP @ ^1.1.1